### ISSUE TITLE
E-Mail all subscribers 

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#126] opened 2022-01-31 10:59 UTC
**E-Mail all subscribers of activity **

We often need to message our class. To copy and paste would be very time-consuming.
There is a bulk select option. could that be hooked to this?
Or would you have a snippet of code that would do this?

**Comment by yoancutillas** [comment] 2022-02-01 09:09
The bulk actions are not implemented unfortunately. 
There is no option to manually send an email to all the participants of an event. I note your feature request, thank you.

However, you can export the participants emails and manually send the email:
- Go to Booking Activities > Bookings
- Select the desired event on the calendar
- The list shouldbe automatically filtered, else, click "Filter the list" button
- Click "Export bookings" button > CSV tab 
- In "Columns to export (ordered)", add "Customer email", and remove the other columns
- Generate export links > Export
- A CSV file is downloaded, open it with Notepad and copy the emails
- Send them an email from your email client (outlook, gmail, etc.) (in Bcc: [docs](https://gravitec.net/blog/how-to-send-email-to-multiple-recipients-without-them-knowing/))

**Comment by rayedgar** [comment] 2022-02-02 18:31
That would be very cumbersome for the admin.  
We have classes of minimal 10 people (15 classes per week).

It's crucial for any booking system to send email to subscribers of an activity. 
Unfortunately, I see when an order is made through Woocommerce the user is displayed with a USER ID instead, without email.

Would it be possible to lookup the USER ID in the Sql table and display all of them in a way it can be copy and paste? or even better, A dedicated 'sent email to to this group'. so without exporting etc but in the bookings section itself.
Or would you have a piece of code that i can insert?

At least for us ( and anyone who run classes or managing groups). It would be the decisive factor in using this booking system.

**Comment by yoancutillas** [comment] 2022-02-04 10:26
I understand and I agree. However, there are currently 229 customer requests on the development backlog that are crucial to their requesters. Each request like yours counts, it increases the development priority and the most requested features are developed ([see the developed features here](https://booking-activities.fr/en/categories/release-notes/)).

I recommend that you choose the booking system that currently best suits your needs and create the custom code that you are missing.

An alternative to exporting would be:
- Go to Booking Activities > Bookings
- Click the settings icon next to "Booking calendar"
- In the "Calendar" tab > in the "Preview booking list columns" option, remove all columns, and add only the "Email" column > OK
- Refresh the page

Now when you go to Booking Activities > Bookings and mouseover the desired event on the calendar, only the emails of the customers who have booked that event will be displayed in the table, making it easy to copy, and paste them in your email client (outlook, gmail, etc.).

**Comment by rayedgar** [comment] 2022-02-04 11:31
I appreciate your reply and workaround. I will see if that is workable. Since this is the only drawback for us. The rest is working great!

Many thanks and will keep a close eye on the developments.



⁣

Hartelijke groet,
Ray Edgar​

On 4 Feb 2022, 11:27, at 11:27, yoancutillas ***@***.***> wrote:
>I understand and I agree. However, there are currently 229 customer
>requests on the development backlog that are crucial to their
>requesters. Each request like yours counts, it increases the
>development priority and the most requested features are developed
>([see the developed features
>here](https://booking-activities.fr/en/categories/release-notes/)).
>
>I recommend that you choose the booking system that currently best
>suits your needs and create the custom code that you are missing.
>
>An alternative to exporting would be:
>- Go to Booking Activities > Bookings
>- Click the settings icon next to "Booking calendar"
>- In the "Calendar" tab > in the "Preview booking list columns" option,
>remove all columns, and add only the "Email" column > OK
>- Refresh the page
>
>Now when you go to Booking Activities > Bookings and mouseover the
>desired event on the calendar, only the emails of the customers who
>have booked that event will be displayed in the table, making it easy
>to copy, and paste them in your email client (outlook, gmail, etc.).
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bookingactivities/booking-activities/issues/126#issuecomment-1029842250
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by yoancutillas** [comment] 2022-02-07 10:51
Duplicate of #112

**Closed by yoancutillas** 2022-02-07 10:51 UTC
Labels: Booking Activities, pending for votes
