### ISSUE TITLE
Refreshed the page and its working as intended now..

### ISSUE THREAD

**Issue by yabdali** [bookingactivities/booking-activities#205] opened 2024-06-11 07:43 UTC
Refreshed the page and its working as intended now..

_Originally posted by @yabdali in https://github.com/bookingactivities/booking-activities/issues/204#issuecomment-2160001619_
            I am wrong, it still shows as duplicate after changing the calendar view from week to month!

**Comment by yoancutillas** [comment] 2024-06-11 08:02
duplicate of #204

**Closed by yoancutillas** 2024-06-11 08:02 UTC
