### ISSUE TITLE
Buying multiple hours

### ISSUE THREAD

**Issue by dgeho1** [bookingactivities/booking-activities#15] opened 2018-05-15 17:23 UTC
www.ymsschedule.org

Is there a method by which one can make it easy for users to buy more than one hour at one time?

There is a place to "add" quantity after choosing a "block" but cannot increase beyond one.

**Comment by bookingactivities** [comment] 2018-05-16 07:47
Hello,

Your customers cannot pick multiple events of their choice.
You can set up groups of events, but then the events will be predefined.

But I have had other requests for this feature, and it is in of the development schedule.

You cannot increase the quantity beyond one because the availability of your events is one. If you set your events' availability to 12, your customers will be able to change the quantity between 1 and 12.

Regards,
Yoan Cutillas

**Comment by graeward** [comment] 2019-07-03 20:08
I like this app very much but I need help.  We are a wedding business.  A user can book a day wedding or an evening wedding.  A day wedding needs an hour and can start anytime between 11 am and 3 pm (preferably on the hour).  An evening wedding can start anywhere between 6 pm and 9 pm.  There are different prices for day and evening weddings.  However, there can only ever be one wedding in any one day.  Can you help with this?

**Comment by pikurasa** [comment] 2019-11-15 15:27
> our customers cannot pick multiple events of their choice.
You can set up groups of events, but then the events will be predefined.

> But I have had other requests for this feature, and it is in of the development schedule.

My customers and I would also greatly benefit from this feature.

Right now, customers have to
1. "select event" --> 2. "click book" (new window) --> 3. "click same product", 4. Repeat one and two until all the desired events are chosen

Perhaps the same functionality that allows the admin to group events can be implemented in the public-facing UI?

**Comment by yoancutillas** [comment] 2019-11-16 09:59
I add your vote, thank you,
Actually this feature is already confirmed, but delayed in favor of other smaller features. It will be a big development that will paralized any others during an extended amount of time.

There is no (known) simple solution or snippet of code to work as a workaround for now unfortunately.

**Comment by yoancutillas** [comment] 2021-01-20 10:16
Released in [1.9.0](https://booking-activities.fr/en/blog/booking-activities-1-9-multiple-bookings-cancel-an-event/)
You can [try the beta](https://booking-activities.fr/en/blog/participate-in-booking-activities-and-add-ons-beta-tests/) now.

**Closed by yoancutillas** 2021-01-20 10:16 UTC
Labels: Booking Activities, approved
