### ISSUE TITLE
notification on stock

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#166] opened 2022-10-13 09:53 UTC
We have spoken about this before but perhaps this makes it more clear.
It would be very useful  to be able to set a message in the calendar as shown in the image.
The difference of the current system is that is cannot display a 'full' (no bookings avail) notification without showing the particle number. Removing this in Css results in removing them on the bookable events.
or is this archievable in Css?

<img width="633" alt="Screenshot 2022-10-13 at 11 44 38" src="https://user-images.githubusercontent.com/6242489/195564289-74472fc0-30f0-4ab4-97e8-3bdfac5bdfb1.png">

**Comment by yoancutillas** [comment] 2022-10-13 12:07
Duplicate of #149

Hello, please see my answer in #149

**Comment by yoancutillas** [comment] 2022-10-13 12:07
Duplicate of #149

**Closed by yoancutillas** 2022-10-13 12:07 UTC

**Comment by rayedgar** [comment] 2022-10-13 12:20
That did it.
Many Thanks!
