### ISSUE TITLE
Double activities displayed on bookings

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#156] opened 2022-07-26 05:52 UTC
Any idea why the activities are displayed double on the booking calendar? There seems to be a relation in showing multiple calendars. Selecting a single resolves it. Selecting multiple calendars and reload displays doubles.

<img width="1250" alt="Screenshot 2022-07-26 at 07 50 44" src="https://user-images.githubusercontent.com/6242489/180933108-7ce11da6-b167-4687-a742-241532922e45.png">

**Comment by yoancutillas** [comment] 2022-07-26 08:45
Can you send me a link to the page where the calendar with the issue is displayed?

**Comment by rayedgar** [comment] 2022-07-26 10:33
It's on the backside. Bookings

⁣

Hartelijke groet,
Ray Edgar​

On 26 Jul 2022, 10:45, at 10:45, yoancutillas ***@***.***> wrote:
>Can you send me a link to the page where the calendar with the issue is
>displayed?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bookingactivities/booking-activities/issues/156#issuecomment-1195189862
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by rayedgar** [comment] 2022-07-27 08:12
BA 1.14.3
Activity pack 1.4.24

YES! load events set to 92 did the job. It was set to 14

Many Thanks

**Comment by yoancutillas** [comment] 2022-07-27 12:31
Thank you,
Yet, the issue is still present, this is only delaying it to occur again.

I don't reproduce it on my site unfortunately,
Do you mind sending me an export of your database tables starting with wp_bookacti so I can investigate the issue at contact@booking-activities.fr?

**Comment by yoancutillas** [comment] 2022-07-28 11:42
Thank you.
The issue doesn't occur on my side unfortunately, do you have any instructions how to reproduce it?

**Comment by rayedgar** [comment] 2022-07-28 13:10
https://user-images.githubusercontent.com/6242489/181513061-67b7ff66-da64-479e-a17a-7a94a528cd54.mov

**Comment by rayedgar** [comment] 2022-07-28 13:15
it seems the culprit is setting show calendar to off. when i set it "Display the calendar by default" to On it seems to be okay

**Comment by yoancutillas** [comment] 2022-08-25 12:06
Thank you for the details, a fix attempt will be released in the next update (1.15.0).
It is an "attempt" because I couldn't reproduce the issue 100% of the time. I am not sure if it really fixed the issue, but the problem never occurred since I made the fix.

**Comment by rayedgar** [comment] 2022-08-25 14:30
Sounds promising. Many thanks.

**Closed** 2022-09-01 22:14 UTC
Labels: bug, Booking Activities, done
