### ISSUE TITLE
Monthly view

### ISSUE THREAD

**Issue by titiph56** [bookingactivities/booking-activities#190] opened 2023-03-27 09:29 UTC
Is it possible to configure the agenda so that it appears directly in monthly view and not weekly ?

Thank you

**Comment by yoancutillas** [comment] 2023-03-27 10:04
Hello, 

You can set the "Month" view by default thanks to the [Display Pack](https://booking-activities.fr/en/downloads/display-pack/) add-on. The option will be in Booking Activities > Booking forms > your form > Calendar settings > Calendar tab > "Initial view".

Duplicate of #86
Duplicate of #176

**Comment by titiph56** [comment] 2023-03-28 12:44
Thank you

**Closed** 2023-03-28 15:27 UTC
Labels: Booking Activities, support
