### ISSUE TITLE
Reschedule to another activity

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#130] opened 2022-02-09 16:42 UTC
We have various ceramic classes. Sometimes we have to reschedule a member. 
I see it is easy to reschedule to the same (clone) of the activity on another date. 
But is there a way to reschedule to another activity? Of course, I can rename the same activity. But to filter out a few of them would be an issue, i think?  We need to filter out sometimes because we give our members doing a course the possibility to book before the course is public. For that I would have to filter and make a special form.

**Comment by yoancutillas** [comment] 2022-02-10 08:27
It is not possible for now unfortunately, I have added your vote, thanks!
You can allow to reschedule to another activity with custom code only, I have updated the custom code in #83 for reference. Set `$admin_only = true;` to allow only administrators to reschedule to any activity. (Continue this thread in #83).

Duplicate of #83

**Comment by yoancutillas** [comment] 2022-02-10 08:27
Duplicate of https://github.com/bookingactivities/booking-activities/issues/83

**Closed by yoancutillas** 2022-02-10 08:27 UTC

**Comment by rayedgar** [comment] 2022-02-11 10:47
That's great!! The only thing s that is shows multiple calendars. Could i narrow that down to only the current calendar?
