### ISSUE TITLE
Waterfall renders underneath change booking dialogue (for admin)

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#51] opened 2020-01-30 20:08 UTC
I recently updated BA and pro plugins and noticed that the waterfall renders behind the change booking dialogue as in:

![Screenshot at 2020-01-30 14:38:01 waterfall](https://user-images.githubusercontent.com/13454579/73485971-0b31e580-439c-11ea-9254-5b36ff6c0a10.png)

This is what I see in the console when I "inspect element":
![Screenshot at 2020-01-30 14:58:24 console cropped](https://user-images.githubusercontent.com/13454579/73486082-48967300-439c-11ea-97eb-3e4acaae33ea.png)

This bug makes it challenging to move dates for clients.

**Comment by yoancutillas** [comment] 2020-01-31 11:53
I don't reproduce this bug on my dev site and on the demo site, 
Can you try to 
- update Booking Activities and its add-ons to their latest versions
- deactivate all your plugins except Booking Activities and Display Pack 
- use Twenty Seventeen instead of your theme, 
- then refresh your browser cache, and your site cache if you are using a cache plugin or a CDN
and tell me if the bug still occurs?

Can you also tell me what browser and what OS you are using?

I remember having fixed this bug a while ago. It was occuring only if the reschedule dialog was moved. Does the problem occur if you don't moved the reschedule dialog?

**Comment by pikurasa** [comment] 2020-01-31 17:03
> I remember having fixed this bug a while ago. It was occuring only if the reschedule dialog was moved. Does the problem occur if you don't moved the reschedule dialog?

I did not move the reschedule dialog.

It would be difficult for me to deactivate theme and plugins at the moment. What I did try is to login via a private window (Firefox), which resulted in the same behavior.

For the short-term, is there a workaround?

**Comment by yoancutillas** [comment] 2020-02-01 10:44
Yes sure, sorry, you can turn the booking method back to calendar instead of waterfall. Add this code in your child theme functions.php:
```
function my_theme_change_reschedule_booking_method( $booking_method ) {
	return 'waterfall';
}
add_filter( 'bookacti_reschedule_booking_method', 'my_theme_change_reschedule_booking_method', 20, 1 );
```

Let me know when you can make the test, at your convenience.

**Comment by pikurasa** [comment] 2020-02-05 15:13
I am still investigating this issue.

> Add this code in your child theme functions.php:

I tried adding this code snippet, but nothing seems to have changed. (I pasted it "as is" -- unsure if I needed to change the name of "my_theme_change" or anything else).

At any rate, from my browser console, I figured out a workaround.

If I change the z-index of .ui-datepicker to something higher (from 99999, I think it was) such as:
```
.ui-datepicker {
	z-index: 100106 !important;
}
```
then it works.

So, maybe just bump the z-index?

**Comment by yoancutillas** [comment] 2020-02-05 17:29
I made a mistake in the code, I corrected it right after publishing, but it was maybe too late when you tried it, make sure your codes reads `return 'calendar';`. I tried it just now on my side, it is working.

I can't bump the z-index before we know where the problem come from, because, maybe the problem come from a third-party plugin which changed z-index for its own use, or maybe this change will create conflicts with other plugins; it would be endless.

**Comment by pikurasa** [comment] 2020-05-03 11:54
To add to this, I cannot see the customer dialogue either when I try and "book for customer". My current workaround is to type part of their name, click enter, and hope that I got it right.

My testing: I tried disabling other plugins, but this did not seem to fix the issue. I have yet to try changing the theme and checking again.

Is there anything else I can do on my end to help debug this issue?

**Comment by yoancutillas** [comment] 2020-05-04 10:21
I can't reproduce it, this is most probably a conflict, deactivate all your plugins and activate [Tweanty Seventeen](https://wordpress.org/themes/twentyseventeen/) instead of your theme. Refresh both your  site cache if you are using a cache plugin / a CDN, and your browser cache (CTRL+F5 usually on the "Bookings" page). Make sure you are using the latest versions of Booking Activities and its add-ons too.

If the problem still occurs in that configuration, I will need administrator credentials to debug it on your site directly (make sure I can use the "plugin editor" under "Plugins" menu).

Note that I do have bumped the CSS z-index in the upcoming version, in the hope that it will improve compatibility. But this wont fix the select2 selectboxes.

**Comment by yoancutillas** [comment] 2021-01-20 10:37
I will close the issue for now, let me know if you can give me access to a site where I can reproduce the issue (all plugins deactivated, Twenty Seventeen theme activated).

**Closed by yoancutillas** 2021-01-20 10:37 UTC
Labels: Display Pack, support
